esphome:
  name: weight-tracker-proxy
  friendly_name: Weight Tracker Proxy

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble_tracker:
  scan_parameters:
    active: false

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

sensor:
  - platform: xiaomi_miscale
    mac_address: !secret miscale_mac_address
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      filters:
        - throttle: 30s

    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: impedance_miscale
      filters:
        - throttle: 30s

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

logger:
  level: INFO
