esphome:
  name: weight-tracker-proxy
  friendly_name: Weight Tracker Proxy

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble_tracker:
  scan_parameters:
    active: false

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

sensor:
  - platform: xiaomi_miscale
    mac_address: !secret miscale_mac_address
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      filters:
        - throttle: 30s
      qos: 2
      retain: false

    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: impedance_miscale
      filters:
        - throttle: 30s
      qos: 2
      retain: false

mqtt:
  broker: !secret mqtt_broker
  port: 8883
  skip_cert_cn_check: true
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIDXjCCAkagAwIBAgIRAOP8R3mZdiUQpdO8ujdfYkEwDQYJKoZIhvcNAQELBQAw
    HzEdMBsGA1UEAxMUVFJBRUZJSyBERUZBVUxUIENFUlQwHhcNMjUwNDEwMjIyNTEy
    WhcNMjYwNDEwMjIyNTEyWjAfMR0wGwYDVQQDExRUUkFFRklLIERFRkFVTFQgQ0VS
    VDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMknVyaspaShFBMwh2RK
    IyAK7I+pDLdKjw4Qpq9oudkVlZkxqjFYmST0o1q78WlNgnG2A3Ky9RjQdmMtVgy5
    fGRSUpRifkVpQegdpjO2474JisT5ZWTm+8UGf0hBCrPl6j5ZL7xvmUAtFc81emX8
    gu0lhxKFdTQlyNy7VwVNyrhiObt/RKvoYvQ0MuvOiNZhOF7lIXZIxNSALmB/NiIr
    ogdppUDAaTmqwhi7xD3K7/RHlasMPeWymw3miOcjUgK2g1Gpc8sjoRfq0Pek2gBO
    qbZEcdawlmBqqa0gOECpjXulM398Qz24HYFpW6uIIMXZY3qJS0rOBFI1zCWoyUAL
    8jECAwEAAaOBlDCBkTAOBgNVHQ8BAf8EBAMCA7gwEwYDVR0lBAwwCgYIKwYBBQUH
    AwEwDAYDVR0TAQH/BAIwADBcBgNVHREEVTBTglE4ZWM5OTA4MmVmNGNhYjRhZmZj
    ODg5ZDY3MDU0MzliZS4xNjgwNDRiMjg2ZjdmODgwYTRiNDc5OThiOTYxYWIzMy50
    cmFlZmlrLmRlZmF1bHQwDQYJKoZIhvcNAQELBQADggEBAHMRlLVlpsP8xZ/TlA6+
    o/j3vxab06Cy0qGu7hVgJdu61bjcYZD7uzhIPdXV01D+9O9EsD5/leegtg/FtfT2
    XKx5XC8B4xfhmEbdsuwVdHiLdxWWYq2BRdePn2wbRwY2eYjlFE0LT3exYrapfMhj
    yYfmqiMOcNUSTBlvya7If631LEiDSnYuq/gOVJLWaxX0gRSfusb4WFlcDUQqq3cu
    G1wh0zOZJZYUiCDHTGpNWpxOH+UrroMhjslR4G2QfxlpF3JuvzofsDpPiauL7Ci2
    KzdCHWzcxrsphRI6FlZhcniBR22LnNW0elpghAIO5LuTZMXewsQdZVSKCbqvKTEb
    dQQ=
    -----END CERTIFICATE-----
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

logger:
  level: INFO
