esphome:
  name: weight-tracker-proxy
  friendly_name: Weight Tracker Proxy

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble_tracker:
  scan_parameters:
    active: false

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

sensor:
  - platform: xiaomi_miscale
    mac_address: !secret miscale_mac_address
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      filters:
        - throttle: 30s
      qos: 2
      retain: false

    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: impedance_miscale
      filters:
        - throttle: 30s
      qos: 2
      retain: false

mqtt:
  broker: !secret mqtt_broker
  port: 8883
  skip_cert_cn_check: true
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIQflnW/hOLl61cOMRRYnXagzANBgkqhkiG9w0BAQsFADAf
    MR0wGwYDVQQDExRUUkFFRklLIERFRkFVTFQgQ0VSVDAeFw0yNTA0MDUwOTEwMDla
    Fw0yNjA0MDUwOTEwMDlaMB8xHTAbBgNVBAMTFFRSQUVGSUsgREVGQVVMVCBDRVJU
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvDytjmHTr3qmK7FWftPh
    /dP95hZRZB413a3gv0tjq6shh4pZeNNVvG7TYPqlr9utvzo1Kx2PVjuglxOlxLvR
    0ltJXRx50MrGfUlaaG3VA0RPQANk9xtcfwK/fg4xgnwQwBg+NZV4OeQmJSxkP/So
    TJ/gG+fJT0PLpINLxFSRA2vDd/gfQU7smSU86JolGlvu1BXVIESSxxyQ9Wbn3PjU
    IC7D8vq5HiqJ5yIOu5fLM8Xl2AEdeT463Ky/ugYtMi0CjZUWdilxKitqWgSJTs4j
    5pr/k/mxUv/QaRa9eINNocOHIS7RJ+oTxQQIDYsf9X6R6ClQCOZZjaaEzZiCjMG5
    DQIDAQABo4GUMIGRMA4GA1UdDwEB/wQEAwIDuDATBgNVHSUEDDAKBggrBgEFBQcD
    ATAMBgNVHRMBAf8EAjAAMFwGA1UdEQRVMFOCUTFjYmU3YjczNTlkNTRiOWNjYmE4
    NDVmNTIyYzkxMDY0LjYyMmFjNTFmZjBhYzAyZTA4ZTQ3NTJkZTRlM2IzNDcyLnRy
    YWVmaWsuZGVmYXVsdDANBgkqhkiG9w0BAQsFAAOCAQEAcVwj6sYAyO3s0DRRqNUg
    YGuVinN4QfUGr++dTwo0cYw8ttGEBr2w0ythOziHLDWaQwGc83ZhsOXr3Khx8mSM
    Is+PAoZ91rkuFLSuE+JdSP+jFTFr8gfuHXM+ak68IAfcsBpe75Yd2+XBs3W+Gcj5
    L+oqYp1MuNnOqkZMZvMLUAzhfo1uwIwPjUEb2vUUtc0GtM6wW3QyWxbg6jLDNgIW
    5TBjC5W0IZt1570GOIAhzb9Hwx3eA6CUdthibJz/FlmRIhCzJJafcNUMUFlLkvl+
    2jpFkQkJSnmXAI9a/ZHq3FDzKx+iHyOtJTyLKn91N3UbkyLvbqXnfisU+DxHSEhf
    2w==
    -----END CERTIFICATE-----
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

logger:
  level: INFO
