esphome:
  name: weight-tracker-proxy
  friendly_name: Weight Tracker Proxy

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble_tracker:
  scan_parameters:
    active: false

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

sensor:
  - platform: xiaomi_miscale
    mac_address: !secret miscale_mac_address
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      filters:
        - throttle: 15s
      qos: 2
      retain: false

    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: impedance_miscale
      filters:
        - throttle: 15s
      qos: 2
      retain: false

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discover_ip: false
  discovery: false
  # Clean state when connecting to MQTT to avoid sending duplicate measurements on reconnection
  on_connect:
    - lambda: |-
        id(weight_miscale).publish_state(0.00);
    - lambda: |-
        id(impedance_miscale).publish_state(0);
  # Clean state when disconnecting from MQTT to avoid sending duplicate measurements on reconnection
  on_disconnect:
    - lambda: |-
        id(weight_miscale).publish_state(0.00);
    - lambda: |-
        id(impedance_miscale).publish_state(0);

logger:
  level: INFO
